--*	DEFINITION
--* 	INIT target="INIT"
--*		PATCH source="INIT" target="DHL TTS 2.0.12" description="TTS 2.0.12 2006-03-27" open="true"
--*	/DEFINITION







--* INIT

CREATE TABLE DBVERSION
( 
	VERSION VARCHAR(20) NOT NULL, 
	TARGET VARCHAR(20), 
	STATEMENTS INTEGER NOT NULL 
)
GO

CREATE TABLE DBVERSIONLOG
( 
	VERSION VARCHAR(20) NOT NULL, 
	TARGET VARCHAR(20) NOT NULL, 
	STATEMENT INTEGER NOT NULL, 
	TIMESTAMP TIMESTAMP NOT NULL, 
	SQLSOURCE LONG VARCHAR NOT NULL, 
	RESULT LONG VARCHAR
)
GO

--* /INIT







--* PATCH source="0.1" target="DHL TTS 2.0.12"

--* /PATCH
